[[plugins]]                                    
repo = 'Shougo/dein.vim'                                          

# ------------------------------------                                    
# colorscheme tender setting                                    
# ------------------------------------
 
# [[plugins]]                                                                                                                                                                                                                                             
# repo = 'jacoborus/tender.vim'                                    
# hook_add = '''                                              
#     colorscheme tender                                      
#     set background=dark                                     
#     syntax on                                               
#     set t_Co=256                                            
#     let $NVIM_TUI_ENABLE_TRUE_COLOR=1                                    
# '''

# ------------------------------------                                    
# Git vim-fugitive                                     
# ------------------------------------                                    
[[plugins]]                                    
repo = 'tpope/vim-fugitive'
hook_add = '''                                    
    nnoremap <silent> gs :Gstatus<CR><C-w>T                                    
    nnoremap <silent> gps :Gpush<CR>                                    
    nnoremap <silent> gpl :Gpull<CR>                                    
'''

[[plugins]]
repo = 'Shougo/deoplete.nvim'
if = 'has("nvim")'
on_i = 1
hook_source = '''
let g:deoplete#enable_at_startup = 1
'''
hook_post_source = '''
let g:deoplete#omni_patterns = {}
'''

[[plugins]]
repo = 'zchee/deoplete-jedi'
on_i = 1
on_ft = 'python'

[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
build = 'git checkout release'
hook_add = """
source ~/.config/nvim/plugins/coc.rc.vim
"""

[[plugins]]
repo = "scrooloose/nerdtree"
hook_add = """
source ~/.config/nvim/plugins/nerdtree.vim
"""

[[plugins]]
repo = 'ryanoasis/vim-devicons'
hook_add = """
source ~/.config/nvim/plugins/devicons.vim
"""

[[plugins]]
repo = "jiangmiao/auto-pairs"
hook_add = """
source ~/.config/nvim/plugins/auto_pairs.vim
"""

[[plugins]]
repo = "itchyny/lightline.vim"
hook_add = """
source ~/.config/nvim/plugins/status_bar.vim
"""

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'ujihisa/unite-colorscheme'

[[plugins]]
repo = 'flazz/vim-colorschemes'

[[plugins]]
repo = "sonjapeterson/1989.vim"
hook_add = """
colorscheme 1989
"""
